### ISSUE TITLE
models.py, create_from_tt_row part 2

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/cap-api#16]
```
    def create_from_tt_row(self, row_num, row):
        <snip>
         elif key == 'publisher':
             volume.publisher = row['publisher']
          else:
              pass
          volume.save()
```
It's probably a good idea to pin this else -> pass down a bit.

The else -> pass here seems to mean the data this function was passed isn't formatted as expected. How serious an offense is this? Without knowing much about the project, I'd imagine that's worth at least a call to logger.warning, if not raising an Exception and calling it quits.

**Comment by anastasia** [comment]
removed in capstone-capapi
