### ISSUE TITLE
case_views.py, check_case_permissions

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/cap-api#30]
Maybe  "check_case_permissions(self, case_count)"  should be called "check_case_allowance"? And "has_case_permissions" should be something like "allowance_sufficient"? I personally find "permission" in this context a little confusing, since it doesn't relate to permissions.py or auth status.

I'm also wondering why check_case_permissions might throw an exception you want to handle explicitly:
```
            try:
                has_case_permissions = self.check_case_permissions(blacklisted_case_count)
            except:
                return JSONResponse({'message': 'Error reading user permissions'}, status=403,)
```
Is that try/except necessary? If so, I'd suggest making it explicit what error might happen and why, by adding a comment and by catching specific exceptions rather than using a blanket "except".

**Comment by anastasia** [comment]
fixed in capstone-capapi
